spring.application.name=FujiFruit
spring.datasource.url=jdbc:mysql://localhost:3306/fruitshop
spring.datasource.username=root
spring.datasource.password=3132004
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework=DEBUG
spring.devtools.restart.enabled=false
server.address=0.0.0.0
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.doc-expansion=none
springdoc.info.title=FujiFruit API
springdoc.info.version=1.0.0
springdoc.info.contact.name=H? tr? FujiFruit
springdoc.info.contact.email=support@fujifruit.com
spring.web.resources.static-locations=file:/static/images/
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
jwt.secret=1234567890abcdefghijklmnopqrstuvwxyz123456789012312312312312311234567890abcdefghijklmnopqrstuvwxyz123456789012312312312312311234567890abcdefghijklmnopqrstuvwxyz12345678901231231231231231
jwt.expiration=3600000
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=/api/vnpay/payment
vnpay.tmnCode=BMEHOAEM
vnpay.hashSecret=OO6JZSB1IQXM4XRQCTCAK12HRDKMG1A3
vnpay.apiUrl=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction